### ISSUE TITLE
Assertion error in Collapse

### ISSUE THREAD

**Issue by rjovelin** [oicr-gsi/debarcer#178]
Testing debarcer with datasets from various library types.

- with haloplex library, it throws an assertion error for 1 genomic interval ( out of ~40): position not recorded in consensus dictionary
Logs can be found under:
/.mounts/labs/gsiprojects/gsi/Debarcer2/rjovelin/test_debarcer_rjdev/haloplex_hs/sample_0/Qsubs/Logs

**Comment by rjovelin** [comment]
Same issue when running debarcer on epic data:
/.mounts/labs/gsiprojects/gsi/Debarcer2/rjovelin/test_debarcer_rjdev/epic_ds/Qsubs/Logs

UmiCollapse_chr2-25456000-25457000_4c7ba0b2-1cd4-4f91-9033-175adb1d6d1e.e3691324
Welcome to texlive/2016
Traceback (most recent call last):
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/debarcer.py", line 770, in <module>
    args.func(args)
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/debarcer.py", line 263, in collapse
    generate_consensus_output(reference, contig, region_start, region_end, bam_file, umi_families, ConsDir, fam_size, pos_threshold, consensus_threshold, count_threshold, max_depth=args.maxdepth, truncate=args.truncate, ignore_orphans=args.ignoreorphans, stepper=args.stepper)
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/src/generate_consensus.py", line 546, in generate_consensus_output
    raw_table_output(cons_data, contig, region_start, region_end, outdir)
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/src/generate_consensus.py", line 449, in raw_table_output
    assert pos in cons_data[f_size]
AssertionError
