### ISSUE TITLE
Issue when computing tick positions

### ISSUE THREAD

**Issue by rjovelin** [oicr-gsi/debarcer#180]
Issue when computing tick positions when a single data point is recorded.
See logs woth simsenseq-pe data: 
/.mounts/labs/gsiprojects/gsi/Debarcer2/rjovelin/test_debarcer_rjdev/epic_ds/Qsubs/Logs

Traceback (most recent call last):
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/debarcer.py", line 770, in <module>
    args.func(args)
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/debarcer.py", line 524, in generate_plots
    PlotMeanFamSize(filename, Colors[1:], Outputfile, 9, 6)
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/src/generate_plots.py", line 485, in PlotMeanFamSize
    ax = CreateMeanFamAx(1, 1, 1, figure, Data, Color, 'Mean family size', region)
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/src/generate_plots.py", line 443, in CreateMeanFamAx
    xtickspos = list(map(lambda x: math.floor(x), [i for i in np.arange(0, len(positions)+1, (len(positions)-1) / 3)]))
ZeroDivisionError: float division by zero

**Comment by rjovelin** [comment]
This issue occurs because collapse didn't complete properly and a single position was recorded in the consensus file before an error was raised during collapsing
