### ISSUE TITLE
Ref base not defined

### ISSUE THREAD

**Issue by rjovelin** [oicr-gsi/debarcer#181]
'ref_base' is not recorded during brouping. Need to investigate why ref base is not a key as expected. Logs under:

/.mounts/labs/gsiprojects/gsi/Debarcer2/rjovelin/test_debarcer_rjdev/simsenseq_pe$ cat Qsubs/Logs/UmiCollapse_chr1-220000000-249250600_84b18419-9fac-46a8-8d84-171197fa6b56.e3696320

Traceback (most recent call last):
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/debarcer.py", line 770, in <module>
    args.func(args)
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/debarcer.py", line 263, in collapse
    generate_consensus_output(reference, contig, region_start, region_end, bam_file, umi_families, ConsDir, fam_size, pos_threshold, consensus_threshold, count_threshold, max_depth=args.maxdepth, truncate=args.truncate, ignore_orphans=args.ignoreorphans, stepper=args.stepper)
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/src/generate_consensus.py", line 539, in generate_consensus_output
    cons_data[f_size] = generate_consensus(umi_families, f_size, contig, region_start, region_end, bam_file, pos_threshold, consensus_threshold, count_threshold, max_depth=max_depth, truncate=truncate, ignore_orphans=ignore_orphans, stepper=stepper)
  File "/u/rjovelin/my_debarcer_rjdev/debarcer/debarcer/src/generate_consensus.py", line 329, in generate_consensus
    ref_base = consensus_seq[pos]['ref_base']
KeyError: 'ref_base'

**Comment by rjovelin** [comment]
Same issue with sureselect data:
/.mounts/labs/gsiprojects/gsi/Debarcer2/rjovelin/test_debarcer_rjdev/sureselect/sample_0/Qsubs/Logs

**Comment by rjovelin** [comment]
This issue arises because of very low coverage in the genomic interval.
For this data, ref_base is not recorded at position 222887935. There is only a single read mapping to this position, and variant at 222887935 is an insertion. In the current code, 'ref_base': ref_base key, value pair is recorded only if the base is not an indel. Although it is expected that debarcer is run with intervals of reasonable coverage (unlike for this run for which I don't know the targeted intervals), it shouldn't be expected that ref_base is recorded only for non-indel bases.
