### ISSUE TITLE
KeyError in VCF Call

### ISSUE THREAD

**Issue by rjovelin** [oicr-gsi/debarcer#183]
KeyError when running call on sureselect data

/.mounts/labs/gsiprojects/gsi/Debarcer2/rjovelin/test_debarcer_rjdev/sureselect/sample_0/Qsubs/Logs/Call_famsize_1_48ae39d2-c159-4ee8-8c07-57e595b19c56.e3836556

Welcome to texlive/2016
Traceback (most recent call last):
  File "/u/rjovelin/my_debarcer_rjdev2/debarcer/debarcer/debarcer.py", line 804, in <module>
    args.func(args)
  File "/u/rjovelin/my_debarcer_rjdev2/debarcer/debarcer/debarcer.py", line 324, in VCF_converter
    WriteVCF(filename, outputfile, args.reference, ref_threshold, alt_threshold, filter_threshold, args.famsize)
  File "/u/rjovelin/my_debarcer_rjdev2/debarcer/debarcer/src/generate_vcf.py", line 158, in WriteVCF
    alt_info = info.format(rawdepth, consdepth, minfam, round(meanfam, 2), depth[ref], ','.join(alt_depth), ','.join(alt_freq))
KeyError: 'AAAAG'

**Comment by rjovelin** [comment]
The issue occurs because AAAAG is recorded as reference base in the consensus file instead of A.
This happens because a single read with a deletion overlaps this position and reference base is assigned the deletion. It should be assigned the base before the deletion event: A

CHROM   POS     REF     A       C       G       T       N       I_(ref,ins)     I_counts        D_(ref,del)     D_counts 
chr1    240138673       AAAAG   0       0       0       0       0                       ('AAAAG', 'A')  1
