### ISSUE TITLE
AssertionError in VCF call

### ISSUE THREAD

**Issue by rjovelin** [oicr-gsi/debarcer#184]
AssertionError when calling variants on sureselect data

/.mounts/labs/gsiprojects/gsi/Debarcer2/rjovelin/test_debarcer_rjdev/sureselect/sample_0/Qsubs/Logs/Call_famsize_10_7a6373fd-31e6-46f1-b6b5-1417f7d97e0b.e3836560

Welcome to texlive/2016
Traceback (most recent call last):
  File "/u/rjovelin/my_debarcer_rjdev2/debarcer/debarcer/debarcer.py", line 804, in <module>
    args.func(args)
  File "/u/rjovelin/my_debarcer_rjdev2/debarcer/debarcer/debarcer.py", line 324, in VCF_converter
    WriteVCF(filename, outputfile, args.reference, ref_threshold, alt_threshold, filter_threshold, args.famsize)
  File "/u/rjovelin/my_debarcer_rjdev2/debarcer/debarcer/src/generate_vcf.py", line 71, in WriteVCF
    consdata = GetConsData(consfile)
  File "/u/rjovelin/my_debarcer_rjdev2/debarcer/debarcer/src/generate_vcf.py", line 43, in GetConsData
    assert pos not in data[contig][famsize]
AssertionError

**Comment by rjovelin** [comment]
fixed
